# Generated by Django 3.0.3 on 2020-03-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_auto_20200309_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
