# Generated by Django 3.0.3 on 2020-03-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0013_auto_20200317_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='Start date: (format YYYY-MM-DD)',
            new_name='start_date',
        ),
    ]
